demo:
  spring:
    client:
      serviceUrl: 10.0.78.74
      port: 12380
      instance:
        renewalInterval: 15
        expirationDuration: 30
      zuul:
        route:
          connections: 100
        total:
          connections: 100