demo:
  spring:
    client:
      logging:
        level: debug
      hikari:
        connection:
          timeout: 600000
        max:
          pool:
            size: 20
      one:
        datasource:
          url: 39.96.85.178:3306
          database: test_db
          username: dev_test
          passord: newretail123
      serviceUrl: http://admin:admin@39.96.85.178:8761/eureka
      instance:
        renewalInterval: 15
        expirationDuration: 30
      zuul:
        route:
          connections: 100
        total:
          connections: 100