custom:
  # 微服务配置
  cloud:
    eureka:
      # 注册中心地址
      service-url: http://admin:admin@39.96.85.178:8761/eureka
    # 心跳配置
    instance:
      renewal-interval: 10
      expiration-duration: 5
  # 日志配置
  logging:
    path: /data/logs/${spring.application.name}/
    level:
      pattern: INFO
      default: DEBUG
  # 数据库配置
  database:
    url: 39.96.85.178:3306
    name: test_db
    username: dev_test
    password: newretail123
    pool:
      max:
        size: 5
        connection: 60000
  # 缓存配置
  redis:
    database: 0
    host: 39.96.85.178
    port: 6379
    password: wgotosg
    timeout: 0
    pool:
      max:
        active: 20
        wait: -1
        idle: 20
      min:
        idle: 0
# 消息队列配置
rabbit:
  product:
    host: 39.96.85.178
    port: 5672
    username: shengong
    password: DYapp123qwe
    virtualHost: /
    topic:
      exchange:
        name: te-match-message
    queue:
      name: q-match-message
    customer:
      request:
        routing: match.loan.req.repayment
