demo:
  spring:
    client:
      logging:
        level: debug
      hikari:
        connection:
          timeout: 600000
        max:
          pool:
            size: 20
      one:
        datasource:
          url: 127.0.0.1:3306
          database: dev
          username: root
          passord: root
      serviceUrl: 10.0.79.86:12380
      instance:
        renewalInterval: 15
        expirationDuration: 30
      zuul:
        route:
          connections: 100
        total:
          connections: 100